//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_GPEntities1 : DbContext
    {
        public DB_GPEntities1()
            : base("name=DB_GPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FreightHead> FreightHeads { get; set; }
        public virtual DbSet<FreightHeadService> FreightHeadServices { get; set; }
        public virtual DbSet<FreightHeadShipmentRate> FreightHeadShipmentRates { get; set; }
    }
}
