//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FreightHead()
        {
            this.FreightHeadServices = new HashSet<FreightHeadService>();
            this.FreightHeadShipmentRates = new HashSet<FreightHeadShipmentRate>();
        }
    
        public int FreightHeadID { get; set; }
        public string FHNumber { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int RequestedByUser { get; set; }
        public Nullable<int> Company { get; set; }
        public string FreightType { get; set; }
        public string IncoTerm { get; set; }
        public string Customer { get; set; }
        public string PickUpLocation { get; set; }
        public string LoadingPort { get; set; }
        public string DischargePort { get; set; }
        public string PlaceOfDelivery { get; set; }
        public string Commodity { get; set; }
        public string FreightCargoType { get; set; }
        public string TraderName { get; set; }
        public string Deparment { get; set; }
        public string Priority { get; set; }
        public int FreightHeadStatusID { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreightHeadService> FreightHeadServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreightHeadShipmentRate> FreightHeadShipmentRates { get; set; }
    }
}
